// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: projection.proto

package projection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Todo item, representing the state.
type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_projection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_projection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_projection_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

// A full snapshot of all todos.
type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todos []*Todo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_projection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_projection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_projection_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

// The core event message that will be streamed.
// The `oneof` field ensures that only one of these messages can be sent at a time.
type ProjectionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*ProjectionEvent_Snapshot
	//	*ProjectionEvent_TodoUpdated
	//	*ProjectionEvent_TodoRemovedId
	//	*ProjectionEvent_SnapshotComplete
	Event isProjectionEvent_Event `protobuf_oneof:"event"`
}

func (x *ProjectionEvent) Reset() {
	*x = ProjectionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_projection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionEvent) ProtoMessage() {}

func (x *ProjectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_projection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionEvent.ProtoReflect.Descriptor instead.
func (*ProjectionEvent) Descriptor() ([]byte, []int) {
	return file_projection_proto_rawDescGZIP(), []int{2}
}

func (m *ProjectionEvent) GetEvent() isProjectionEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ProjectionEvent) GetSnapshot() *Snapshot {
	if x, ok := x.GetEvent().(*ProjectionEvent_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *ProjectionEvent) GetTodoUpdated() *Todo {
	if x, ok := x.GetEvent().(*ProjectionEvent_TodoUpdated); ok {
		return x.TodoUpdated
	}
	return nil
}

func (x *ProjectionEvent) GetTodoRemovedId() string {
	if x, ok := x.GetEvent().(*ProjectionEvent_TodoRemovedId); ok {
		return x.TodoRemovedId
	}
	return ""
}

func (x *ProjectionEvent) GetSnapshotComplete() *emptypb.Empty {
	if x, ok := x.GetEvent().(*ProjectionEvent_SnapshotComplete); ok {
		return x.SnapshotComplete
	}
	return nil
}

type isProjectionEvent_Event interface {
	isProjectionEvent_Event()
}

type ProjectionEvent_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type ProjectionEvent_TodoUpdated struct {
	TodoUpdated *Todo `protobuf:"bytes,2,opt,name=todo_updated,json=todoUpdated,proto3,oneof"`
}

type ProjectionEvent_TodoRemovedId struct {
	TodoRemovedId string `protobuf:"bytes,3,opt,name=todo_removed_id,json=todoRemovedId,proto3,oneof"` // We only need the ID to remove a todo.
}

type ProjectionEvent_SnapshotComplete struct {
	SnapshotComplete *emptypb.Empty `protobuf:"bytes,4,opt,name=snapshot_complete,json=snapshotComplete,proto3,oneof"`
}

func (*ProjectionEvent_Snapshot) isProjectionEvent_Event() {}

func (*ProjectionEvent_TodoUpdated) isProjectionEvent_Event() {}

func (*ProjectionEvent_TodoRemovedId) isProjectionEvent_Event() {}

func (*ProjectionEvent_SnapshotComplete) isProjectionEvent_Event() {}

var File_projection_proto protoreflect.FileDescriptor

var file_projection_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x04, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x32, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x6f, 0x64, 0x6f, 0x52, 0x05, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x22, 0xf6, 0x01, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x32, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x74, 0x6f, 0x64, 0x6f, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x48, 0x00, 0x52, 0x0b, 0x74,
	0x6f, 0x64, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x6f,
	0x64, 0x6f, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x11, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x10, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x32, 0x57, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x3b, 0x5a,
	0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x64, 0x6f,
	0x73, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_projection_proto_rawDescOnce sync.Once
	file_projection_proto_rawDescData = file_projection_proto_rawDesc
)

func file_projection_proto_rawDescGZIP() []byte {
	file_projection_proto_rawDescOnce.Do(func() {
		file_projection_proto_rawDescData = protoimpl.X.CompressGZIP(file_projection_proto_rawDescData)
	})
	return file_projection_proto_rawDescData
}

var file_projection_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_projection_proto_goTypes = []interface{}{
	(*Todo)(nil),            // 0: projection.Todo
	(*Snapshot)(nil),        // 1: projection.Snapshot
	(*ProjectionEvent)(nil), // 2: projection.ProjectionEvent
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_projection_proto_depIdxs = []int32{
	0, // 0: projection.Snapshot.todos:type_name -> projection.Todo
	1, // 1: projection.ProjectionEvent.snapshot:type_name -> projection.Snapshot
	0, // 2: projection.ProjectionEvent.todo_updated:type_name -> projection.Todo
	3, // 3: projection.ProjectionEvent.snapshot_complete:type_name -> google.protobuf.Empty
	3, // 4: projection.ProjectionService.Subscribe:input_type -> google.protobuf.Empty
	2, // 5: projection.ProjectionService.Subscribe:output_type -> projection.ProjectionEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_projection_proto_init() }
func file_projection_proto_init() {
	if File_projection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_projection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_projection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_projection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_projection_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ProjectionEvent_Snapshot)(nil),
		(*ProjectionEvent_TodoUpdated)(nil),
		(*ProjectionEvent_TodoRemovedId)(nil),
		(*ProjectionEvent_SnapshotComplete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_projection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projection_proto_goTypes,
		DependencyIndexes: file_projection_proto_depIdxs,
		MessageInfos:      file_projection_proto_msgTypes,
	}.Build()
	File_projection_proto = out.File
	file_projection_proto_rawDesc = nil
	file_projection_proto_goTypes = nil
	file_projection_proto_depIdxs = nil
}
